export default {
  favor:  require("../../../images/icon/favor/favor.png"),
  favor_fill: require("../../../images/icon/favor/favor_fill.png"),
  collection: require("../../../images/icon/favor/collection.png"),
  collection_fill: require("../../../images/icon/favor/collection_fill.png"),
  homepage: require("../../../images/icon/home/homepage.png"),
  homepage_fill: require("../../../images/icon/home/homepage_fill.png"),
  interactive: require("../../../images/icon/comment/interactive.png"),
  interactive_fill: require("../../../images/icon/comment/interactive_fill.png"),
  manage: require("../../../images/icon/manage/manage.png"),
  manage_fill: require("../../../images/icon/manage/manage_fill.png"),
  menu: require("../../../images/icon/menu/menu.png"),
  defaultAvatar: require("../../../images/icon/avatar/defaultAvatar.jpg"),
  download: require("../../../images/icon/download/download2.png"),
  search: require("../../../images/icon/search/search2.png"),
  layers: require("../../../images/icon/layers/layers.png"),
  find: require("../../../images/icon/find/find.png"),
}