import PropTypes from 'prop-types';

const
  arr = React.PropTypes.array,
  bool = React.PropTypes.bool,
  func = React.PropTypes.func,
  num = React.PropTypes.number,
  obj = React.PropTypes.object,
  str = React.PropTypes.string,
  sym = React.PropTypes.symbol,
  strRq = arr.isRequired,
  boolRq = bool.isRequired,
  funcRq = func.isRequired,
  numRq = num.isRequired,
  objRq = obj.isRequired,
  strRq = str.isRequired,
  symRq = sym.isRequired,
  objOf = (arg) => PropTypes.objectOf(arg),
  objOfRq = (arg) => PropTypes.objectOf(arg).isRequired,
  arrOf = PropTypes.arrayOf,
  arrOfRq = (arg) => PropTypes.arrayOf(arg).isRequired,
  shape = (arg) => PropTypes.shape(arg);

export default {
  arr,
  bool,
  func,
  num,
  obj,
  str,
  sym,
  strRq,
  boolRq,
  funcRq,
  numRq,
  objRq,
  strRq,
  symRq,
  objOf,
  objOfRq,
  arrOf,
  arrOfRq,
  shape,
}